"use client";
import { useState } from 'react';
import type { Contract } from '../../server/orchestration/types';
import { GoalActivity } from './goal-activity';
import { CheckEvidence } from './check-evidence';
import { GoalTeam } from './goal-team';
import { WaveBoard } from './wave-board';
import { attention } from './attention';
import type { Action, Goal } from './goal-board';
import { goalStage } from './goal-fleet';
export function GoalDetail({ goal, disabled, terminal, act, control }: {
  goal: Goal & { contracts: { revision: number; contract: Contract }[] }; disabled: boolean; terminal: boolean;
  act(goal: Goal, action: Action): Promise<boolean>; control(goal: Goal, action: 'terminal' | 'reconcile', attemptId?: string): Promise<void>;
}) {
  const tabs = ['Overview', 'Waves & sessions', 'Team & models', 'Run report', 'Activity'] as const;
  const [tab, setTab] = useState<typeof tabs[number]>('Overview');
  const [feedback, setFeedback] = useState('');
  const [answer, setAnswer] = useState('');
  const clarification = goal.actions.find(action => action.type === 'answer_clarification');
  const [editingTitle, setEditingTitle] = useState(false), [title, setTitle] = useState(goal.title);
  const rename = goal.actions.find(action => action.type === 'rename_goal');
  const contract = goal.contracts.find(entry => entry.revision === goal.revision)?.contract;
  const revision = goal.actions.find(action => action.type === 'request_revision');
  const safeLink = goal.pr?.url && /^https:\/\//.test(goal.pr.url) ? goal.pr.url : null;
  return <article className="orch-detail" aria-label="Goal detail">
    <section className="orch-card"><div className="orch-eyebrow">{goalStage(goal)} · PLAN {goal.revision}</div><h1>{goal.title}</h1>{rename && (editingTitle ? <form onSubmit={event => { event.preventDefault(); void act(goal, { ...rename, payload: { title } }).then(saved => { if (saved) setEditingTitle(false); }); }}><label>Goal title<input value={title} maxLength={100} onChange={event => setTitle(event.target.value)} disabled={disabled} required /></label><button disabled={disabled || !title.trim()}>Save title</button><button type="button" onClick={() => setEditingTitle(false)}>Cancel</button></form> : <button disabled={disabled} onClick={() => { setTitle(goal.title); setEditingTitle(true); }}>Edit title</button>)}
      <p className="orch-description">{goal.description || goal.title}</p><p>{goal.plannerName}</p>{attention(goal) && <p className="orch-banner">{attention(goal)}</p>}
      {goal.hold && goal.recoveryBlocked && <p role="status">{goal.recoveryBlocked}</p>}
      <details><summary>Source and technical details</summary><p>Base branch: {goal.baseBranch}</p><p>Integrated head <code>{goal.integrationHead.slice(0, 12) || 'Preparing fresh base…'}</code></p><button disabled={disabled} onClick={() => void control(goal, 'reconcile')}>Reconcile workers</button></details>
      {safeLink && <a className="orch-pr" href={safeLink} target="_blank" rel="noreferrer">Open pull request #{goal.pr?.number}</a>}
      {goal.status === 'delivered' && <p role="status">{goal.mergeSync?.state === 'closed' ? 'Closed without merging on GitHub.' : goal.mergeSync?.error || 'Waiting for merge on GitHub.'} {goal.mergeSync ? `Last checked ${new Date(goal.mergeSync.checkedAt).toLocaleString()}.` : 'First merge check pending.'} Checks run every 15 minutes while your Mac is online.</p>}
      {goal.publication?.observation && <p>Publication: {goal.publication.observation.status}</p>}
      {goal.publication?.observation?.status === 'target_moved' && <p className="orch-banner">The target branch moved to <code>{goal.publication.observation.baseHeadSha?.slice(0, 12) ?? 'an unavailable commit'}</code>. Publishing keeps the reviewed and verified head above unchanged; it does not rebase or merge the target branch.</p>}
      {goal.status === 'awaiting_approval' && goal.team && <p>Approval includes this design, plan, verification and proposed team.</p>}
      {goal.status === 'awaiting_approval' && goal.approvalBlocked && <p className="orch-banner">{goal.approvalBlocked}</p>}
      <div className="orch-actions">{goal.actions.filter(action => action.type !== 'request_revision' && action.type !== 'resume_planner' && action.type !== 'rename_goal' && action.type !== 'answer_clarification').map(action => <button key={`${action.type}:${JSON.stringify(action.payload)}`} disabled={disabled} onClick={() => void act(goal, action)}>{action.label}</button>)}</div>
    </section>
    {clarification && <form className="orch-card" onSubmit={event => { event.preventDefault(); void act(goal, { ...clarification, payload: { answer } }).then(saved => { if (saved) setAnswer(''); }); }}><h3>A question from your planner</h3><p>{goal.clarification?.question}</p><label>Your answer<textarea value={answer} onChange={event => setAnswer(event.target.value)} maxLength={8000} disabled={disabled} required /></label><button disabled={disabled || !answer.trim()}>Send answer</button></form>}
    <div className="mission-detail-tabs" role="tablist" aria-label="Goal sections">{tabs.map(name => <button key={name} id={`goal-tab-${tabs.indexOf(name)}`} role="tab" aria-selected={tab === name} aria-controls="goal-section" tabIndex={tab === name ? 0 : -1} onKeyDown={event => { const index = tabs.indexOf(name); const next = event.key === 'ArrowRight' ? (index + 1) % tabs.length : event.key === 'ArrowLeft' ? (index + tabs.length - 1) % tabs.length : event.key === 'Home' ? 0 : event.key === 'End' ? tabs.length - 1 : null; if (next !== null) { event.preventDefault(); setTab(tabs[next]); document.getElementById(`goal-tab-${next}`)?.focus(); } }} onClick={() => setTab(name)}>{name}</button>)}</div>
    <div role="tabpanel" id="goal-section" aria-labelledby={`goal-tab-${tabs.indexOf(tab)}`}>
    {tab === 'Overview' && Boolean(goal.references?.length) && <section className="orch-card"><h3>Reference files</h3><ul>{goal.references.map(reference => <li key={reference.id}><a href={`/api/orchestration/goals/${encodeURIComponent(goal.id)}/references/${reference.id}`} target="_blank" rel="noreferrer">{reference.name}</a> <small>{Math.ceil(reference.bytes / 1024)} KiB · {reference.mimeType}</small></li>)}</ul></section>}
    {tab === 'Overview' && contract && <section className="orch-card"><h3>Proposed contract</h3><p>{contract.outcome}</p><h4>Scope</h4><ul>{contract.scope.map(item => <li key={item}>{item}</li>)}</ul><h4>Out of scope</h4><ul>{contract.exclusions.map(item => <li key={item}>{item}</li>)}</ul><h4>Acceptance criteria</h4><ul>{contract.criteria.map(item => <li key={item.id}>{item.text} <small>Verified by {item.verification}</small></li>)}</ul><details><summary>Verification for this goal</summary>{contract.verification.map(check => <p key={check.id}><strong>{check.id}</strong> <code>{check.argv.join(' ')}</code></p>)}</details></section>}
    {tab === 'Overview' && revision && <form className="orch-card" onSubmit={event => { event.preventDefault(); void act(goal, { ...revision, payload: { message: feedback } }).then(saved => { if (saved) setFeedback(''); }); }}><label>Revision feedback<textarea rows={2} maxLength={8000} value={feedback} onChange={event => setFeedback(event.target.value)} disabled={disabled} required /></label><button disabled={disabled || !feedback.trim()}>Request revision</button></form>}
    {tab === 'Team & models' && <GoalTeam goal={goal} disabled={disabled} act={act} />}
    {tab === 'Waves & sessions' && <WaveBoard goal={goal} />}
    {tab === 'Activity' && <GoalActivity goalId={goal.id} version={goal.version} />}
    {(tab === 'Waves & sessions') && <section className="orch-card"><h3>Agent activity</h3>{goal.attempts.map(attempt => <div className="orch-attempt" key={attempt.id}><strong>{attempt.role === 'planner' ? goal.plannerName : attempt.role}{attempt.taskId ? ` · ${attempt.taskId}` : ''}</strong>{attempt.assignment && <small>{attempt.assignment.label} · {attempt.assignment.model}</small>}<span>{attempt.status} · worker {attempt.workerState}{attempt.current ? '' : ' · historical'}</span>{attempt.workerState === 'unknown' && <p className="orch-banner">Ownership is uncertain. Capacity stays reserved until reconciliation confirms termination.</p>}{attempt.error && <p>{attempt.error}</p>}{attempt.current && attempt.workerState === 'running' && <details><summary>{attempt.role === 'planner' ? 'Planning session' : 'Agent session'}</summary><div className="orch-actions"><button disabled={disabled || !terminal} onClick={() => void control(goal, 'terminal', attempt.id)}>{attempt.role === 'planner' ? 'Open planning terminal' : `Open ${attempt.role} terminal`}</button>{goal.actions.filter(action => action.type === 'resume_planner' && action.payload.attemptId === attempt.id).map(action => <button key={action.type} disabled={disabled || !terminal} onClick={() => void act(goal, action)}>{action.label}</button>)}{!terminal && <small>This adapter has no native terminal.</small>}</div></details>}</div>)}</section>}
    {tab === 'Run report' && (goal.integration || Boolean(goal.integrationResults?.length)) && <section className="orch-card"><h3>Integration</h3>{goal.integration && <p>{goal.integration.state} · {goal.integration.taskId || 'Combined output'}{goal.integration.code && ` · ${goal.integration.code}`}</p>}{goal.integrationResults?.map(result => <p key={result.operationId}>{result.taskId || 'Combined repair'} integrated at <code>{result.headSha.slice(0, 12)}</code></p>)}</section>}
    {tab === 'Run report' && goal.reviews.length > 0 && <section className="orch-card"><h3>Independent reviews</h3>{goal.reviews.length === 0 && <p>No review evidence yet.</p>}{goal.reviews.map(review => <div className="orch-review" key={review.id}><strong>{review.kind}{review.taskId ? ` · ${review.taskId}` : ''}: {review.disposition.replaceAll('_', ' ')}</strong><p>Target <code>{review.target.startsWith('contract:') ? review.target : review.target.slice(0, 12)}</code></p>{review.findings.map(finding => <blockquote key={finding.id}><strong>{finding.blocking ? 'Blocking' : finding.severity}: {finding.title}</strong><p>{finding.evidence}</p><p>{finding.suggestion}</p></blockquote>)}</div>)}</section>}
    {tab === 'Run report' && goal.verification && <section className="orch-card" aria-label="Combined verification"><h3>Combined verification</h3>{goal.verification ? <><p>Checked head <code>{goal.verification.headSha.slice(0, 12)}</code></p>{goal.verification.checks.map(check => <div key={check.id}><p><strong>{check.id}</strong> · {check.passed ? 'Passed' : 'Failed'}</p><CheckEvidence goalId={goal.id} artifactId={check.artifactId} /></div>)}</> : <p>No completed verification for the current combined head.</p>}</section>}
    {tab === 'Run report' && goal.verificationRuns?.length > 0 && <section className="orch-card"><h3>Verification runs</h3>{goal.verificationRuns.map(run => <section key={run.operationId}><h4>{run.waveId ? `Wave ${run.waveId}` : 'Combined output'} · plan {run.revision}</h4><p>{run.status} · worker {run.workerState}{run.current ? '' : ' · historical'} · <code>{run.headSha.slice(0, 12)}</code></p>{run.verification?.checks.map(check => <div key={check.id}><p><strong>{check.id}</strong> · {check.passed ? 'Passed' : 'Failed'}</p><CheckEvidence goalId={goal.id} artifactId={check.artifactId} /></div>)}</section>)}</section>}
    {tab === 'Run report' && !goal.verification && goal.reviews.length === 0 && <section className="orch-card"><h3>No review or verification evidence yet</h3><p>Results will appear here as the goal progresses.</p></section>}
    {tab === 'Overview' && !contract && <section className="orch-card"><h3>Planning the outcome</h3><p>The planner is preparing the design, acceptance criteria and execution plan.</p></section>}
    </div>
  </article>;
}
