"use client";
import { useState } from 'react';
import type { Contract } from '../../server/orchestration/types';
import type { Action, Goal } from './goal-board';
export function GoalDetail({ goal, disabled, terminal, act, control }: {
  goal: Goal & { contracts: { revision: number; contract: Contract }[] }; disabled: boolean; terminal: boolean;
  act(goal: Goal, action: Action): Promise<boolean>; control(goal: Goal, action: 'terminal' | 'reconcile', attemptId?: string): Promise<void>;
}) {
  const [feedback, setFeedback] = useState('');
  const contract = goal.contracts.find(entry => entry.revision === goal.revision)?.contract;
  const revision = goal.actions.find(action => action.type === 'request_revision');
  const safeLink = goal.pr?.url && /^https:\/\//.test(goal.pr.url) ? goal.pr.url : null;
  return <article className="orch-detail" aria-label="Goal detail">
    <section className="orch-card"><div className="orch-eyebrow">{goal.status.replaceAll('_', ' ')} · REVISION {goal.revision}</div><h2>{goal.title}</h2>
      <p>Integrated head <code>{goal.integrationHead.slice(0, 12)}</code></p>
      {safeLink && <a className="orch-pr" href={safeLink} target="_blank" rel="noreferrer">Open pull request #{goal.pr?.number}</a>}
      {goal.publication?.observation && <p>Publication: {goal.publication.observation.status}</p>}
      {goal.publication?.observation?.status === 'target_moved' && <p className="orch-banner">The target branch moved to <code>{goal.publication.observation.baseHeadSha?.slice(0, 12) ?? 'an unavailable commit'}</code>. Publishing keeps the reviewed and verified head above unchanged; it does not rebase or merge the target branch.</p>}
      {goal.status === 'awaiting_approval' && goal.approvalBlocked && <p className="orch-banner">{goal.approvalBlocked}</p>}
      <div className="orch-actions">{goal.actions.filter(action => action.type !== 'request_revision' && action.type !== 'resume_planner').map(action => <button key={`${action.type}:${JSON.stringify(action.payload)}`} disabled={disabled} onClick={() => void act(goal, action)}>{action.label}</button>)}<button disabled={disabled} onClick={() => void control(goal, 'reconcile')}>Reconcile workers</button></div>
    </section>
    {contract && <section className="orch-card"><h3>Proposed contract</h3><p>{contract.outcome}</p><h4>Scope</h4><ul>{contract.scope.map(item => <li key={item}>{item}</li>)}</ul><h4>Out of scope</h4><ul>{contract.exclusions.map(item => <li key={item}>{item}</li>)}</ul><h4>Acceptance criteria</h4><ul>{contract.criteria.map(item => <li key={item.id}>{item.text} <small>Verified by {item.verification}</small></li>)}</ul><details><summary>Required repository checks</summary>{contract.verification.map(check => <p key={check.id}><strong>{check.id}</strong> <code>{check.argv.join(' ')}</code></p>)}</details></section>}
    {revision && <form className="orch-card" onSubmit={event => { event.preventDefault(); void act(goal, { ...revision, payload: { message: feedback } }).then(saved => { if (saved) setFeedback(''); }); }}><label>Revision feedback<textarea rows={2} maxLength={8000} value={feedback} onChange={event => setFeedback(event.target.value)} disabled={disabled} required /></label><button disabled={disabled || !feedback.trim()}>Request revision</button></form>}
    <section className="orch-card"><h3>Task graph</h3>{goal.tasks.length === 0 && <p>The planner has not published a task graph yet.</p>}<ol className="orch-task-grid">{goal.tasks.map(task => <li key={task.id} data-task={task.id}><div><strong>{task.id} · {task.title}</strong><span className="orch-state">{task.status.replaceAll('_', ' ')}</span></div><p>{task.dependsOn.length ? `Depends on ${task.dependsOn.join(', ')}` : 'Independent task'}</p><small>Repairs: {task.repairCount} / {task.repairLimit}</small>{task.integratedSha && <p>Integrated <code>{task.integratedSha.slice(0, 12)}</code></p>}</li>)}</ol></section>
    <section className="orch-card"><h3>Agent activity</h3>{goal.attempts.map(attempt => <div className="orch-attempt" key={attempt.id}><strong>{attempt.role}{attempt.taskId ? ` · ${attempt.taskId}` : ''}</strong><span>{attempt.status} · worker {attempt.workerState}{attempt.current ? '' : ' · historical'}</span>{attempt.workerState === 'unknown' && <p className="orch-banner">Ownership is uncertain. Capacity stays reserved until reconciliation confirms termination.</p>}{attempt.error && <p>{attempt.error}</p>}{attempt.current && attempt.role === 'planner' && attempt.workerState === 'running' && <div className="orch-actions"><button disabled={disabled || !terminal} onClick={() => void control(goal, 'terminal', attempt.id)}>Open planning terminal</button>{goal.actions.filter(action => action.type === 'resume_planner' && action.payload.attemptId === attempt.id).map(action => <button key={action.type} disabled={disabled || !terminal} onClick={() => void act(goal, action)}>{action.label}</button>)}{!terminal && <small>This adapter has no native terminal.</small>}</div>}</div>)}</section>
    <section className="orch-card"><h3>Independent reviews</h3>{goal.reviews.length === 0 && <p>No review evidence yet.</p>}{goal.reviews.map(review => <div className="orch-review" key={review.id}><strong>{review.kind}{review.taskId ? ` · ${review.taskId}` : ''}: {review.disposition.replaceAll('_', ' ')}</strong><p>Target <code>{review.target.startsWith('contract:') ? review.target : review.target.slice(0, 12)}</code></p>{review.findings.map(finding => <blockquote key={finding.id}><strong>{finding.blocking ? 'Blocking' : finding.severity}: {finding.title}</strong><p>{finding.evidence}</p><p>{finding.suggestion}</p></blockquote>)}</div>)}</section>
    <section className="orch-card" aria-label="Combined verification"><h3>Combined verification</h3>{goal.verification ? <><p>Checked head <code>{goal.verification.headSha.slice(0, 12)}</code></p>{goal.verification.checks.map(check => <p key={check.id}><strong>{check.id}</strong> · {check.passed ? 'Passed' : 'Failed'}</p>)}</> : <p>No completed verification for the current combined head.</p>}</section>
  </article>;
}
