const settingsSuite = Cypress.expose('settings') ? describe : describe.skip;
settingsSuite('Local settings and onboarding with a real disposable service', () => {
  it('pairs, adds a project, configures a provider and retains the settings on refresh', () => {
    cy.viewport(390, 844);
    cy.visit('/onboarding');
    cy.findByLabelText('Pairing code').should('be.visible');
    cy.task<string>('settingsPairing', null, { log: false }).then(token => {
      cy.findByLabelText('Pairing code').type(token, { log: false });
      cy.findByRole('button', { name: 'Pair this device' }).click();
    });
    cy.findByText('No projects configured yet.').should('be.visible');
    cy.task<string>('settingsProjectPath').then(path => cy.findByLabelText('Project directory').type(path));
    cy.findByRole('button', { name: 'Validate and add project' }).click();
    cy.findByLabelText('Project name').clear().type('My open-source project');
    cy.findByLabelText('GitHub destination').type('example/disposable');
    cy.findByLabelText('Git remote').type('git@github.com:example/disposable.git');
    cy.findByRole('button', { name: 'Add verification command' }).click();
    cy.findByLabelText('Default provider').select('codex');
    cy.findByLabelText('Background agents').clear().type('3');
    cy.findByRole('button', { name: 'Complete setup' }).click();
    cy.findByText('Setup complete. You can start a goal.').should('be.visible');
    cy.reload();
    cy.findByLabelText('Project name').should('have.value', 'My open-source project');
    cy.findByLabelText('Default provider').should('have.value', 'codex');
    cy.findByLabelText('Background agents').should('have.value', '3');
    cy.screenshot('settings-onboarding-mobile');
    cy.visit('/orchestration');
    cy.findByLabelText('Repository').find('option').should('contain.text', 'My open-source project');
    cy.findByLabelText('What should we accomplish?').type('Plan a disposable change');
    cy.findByRole('button', { name: 'Start planning' }).click();
    cy.findByRole('navigation', { name: 'Goals' }).should('contain.text', 'Plan a disposable change');
    cy.findByRole('link', { name: 'Manage projects and providers' }).click();
    cy.findByLabelText('Enabled for new goals').uncheck();
    cy.findByRole('button', { name: 'Save settings' }).click();
    cy.findByText('Settings saved on this Mac.').should('be.visible');
    cy.visit('/orchestration');
    cy.findByRole('button', { name: 'Start planning' }).should('be.disabled');
    cy.findByRole('navigation', { name: 'Goals' }).should('contain.text', 'Plan a disposable change');
  });
});
