"use client";
/* eslint-disable jsx-a11y/no-autofocus, jsx-a11y/label-has-associated-control, @next/next/no-img-element */

import { FormEvent, useCallback, useEffect, useMemo, useRef, useState } from "react";
import { AppsView, type Preview } from "./apps-view";
import { localUrlPort, splitContextLinks, terminalContext } from "./context-links.mjs";
import { MarkdownViewer } from "./markdown-viewer";
import { slashShortcuts } from "./slash-shortcuts.mjs";
import { isNearBottom, nextFollowState } from "./terminal-follow.mjs";
import { TerminalGrid, type TerminalView } from "./terminal-grid.tsx";
import { terminalViewSignature } from "./terminal-grid.mjs";
import { WorktreeDashboardView } from "./worktree-dashboard";

type Terminal = { id: string; title: string; current_directory?: string | null; is_focused?: boolean; is_ready?: boolean };
type WorkspaceStatus = { effective?: string; inferred?: string; signals?: Record<string, boolean> };
type Workspace = { id: string; title: string; current_directory?: string | null; has_unread?: boolean; is_selected?: boolean; last_activity_at?: number; preview?: string | null; listening_ports?: number[]; terminals: Terminal[]; status?: WorkspaceStatus | null };
type Bootstrap = { connected: boolean; host: { mac_display_name?: string; workspace_count?: number } | null; workspaces: Workspace[]; error: string | null; refreshedAt: string };
type Repo = { id: string; name: string; root: string; path: string; branch: string; ahead: number; behind: number; changedFiles: number; dirty: boolean; lastActivity: number; scripts: string[] };
type InboxItem = { id: string; requestId?: string; type: "request" | "notification"; kind: string; workspaceId?: string | null; surfaceId?: string | null; title: string; subtitle?: string | null; body?: string; toolName?: string | null; toolInput?: unknown; questionOptions?: Array<string | { label?: string; value?: string }> };
type Inbox = { items: InboxItem[]; actionableCount: number; unreadCount: number };
type Todo = { id: string; text: string; state: string; origin?: string };
type Overview = { status: WorkspaceStatus; todos: { items: Todo[]; progress: { completed: number; total: number; first_unchecked_text?: string | null } }; metrics: { cpuPercent: number; memoryBytes: number; processCount: number } | null; surfaceHealth: { surfaces?: Array<{ id: string; type: string; in_window: boolean }> } | null };
type ChangedFile = { path: string; status: string; area: string; areas: string[] };
type Changes = { repo: Repo; files: ChangedFile[]; summary: { staged: string; unstaged: string }; recentCommit?: { hash: string; subject: string } | null };
type PullRequest = { number: number; title: string; url: string; state: string; isDraft: boolean; reviewDecision: string; mergeState: string; headBranch: string; baseBranch: string; updatedAt?: string | null; author?: string | null; checks: { passed: number; failed: number; pending: number; total: number } };
type ImageAttachment = { path: string; name: string; mime: string; size: number; preview: string };
type PromptQueueItem = { id: string; workspaceId: string; surfaceId: string; text: string; createdAt: string; updatedAt: string; attempts: number; lastError?: string | null };
type View = "sessions" | "inbox" | "launch" | "apps" | "settings";
type DetailTab = "terminal" | "tasks" | "changes";
type HomeMode = "sessions" | "worktrees";

async function api<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(path, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } });
  const body = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(body.error || `Request failed (${response.status})`);
  return body as T;
}

function compactPath(path?: string | null) { return path ? path.replace(/^\/Users\/[^/]+/, "~") : "Directory unavailable"; }
function relativeTime(timestamp?: number) { if (!timestamp) return "now"; const seconds = Math.max(0, Math.round(Date.now() / 1000 - timestamp)); if (seconds < 60) return "now"; if (seconds < 3600) return `${Math.floor(seconds / 60)}m`; if (seconds < 86400) return `${Math.floor(seconds / 3600)}h`; return `${Math.floor(seconds / 86400)}d`; }
function sessionState(workspace: Workspace) { if (workspace.has_unread || workspace.status?.signals?.any_agent_needs_input) return { label: "Needs you", tone: "attention" }; if (workspace.status?.effective === "working" || workspace.status?.signals?.any_agent_running) return { label: "Working", tone: "working" }; if (workspace.status?.effective === "done") return { label: "Done", tone: "done" }; return { label: "Ready", tone: "ready" }; }
function formatBytes(bytes = 0) { if (bytes < 1024 ** 2) return `${Math.round(bytes / 1024)} KB`; if (bytes < 1024 ** 3) return `${(bytes / 1024 ** 2).toFixed(0)} MB`; return `${(bytes / 1024 ** 3).toFixed(1)} GB`; }
function imageDataUrl(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error("Could not read that image")); reader.readAsDataURL(file); }); }
function composedPrompt(draft: string, attachments: ImageAttachment[]) { const imageLines = attachments.map((image) => `- ${image.path}`); return [draft.trim(), imageLines.length ? `Attached image${imageLines.length > 1 ? "s" : ""}:\n${imageLines.join("\n")}` : ""].filter(Boolean).join("\n\n"); }

export default function Home() {
  const [auth, setAuth] = useState<"loading" | "paired" | "unpaired" | "offline">("loading");
  const [pairingToken, setPairingToken] = useState(""); const [pairingError, setPairingError] = useState("");
  const [bootstrap, setBootstrap] = useState<Bootstrap | null>(null); const [inbox, setInbox] = useState<Inbox>({ items: [], actionableCount: 0, unreadCount: 0 }); const [repos, setRepos] = useState<Repo[]>([]);
  const [view, setView] = useState<View>(() => { if (typeof window === "undefined") return "sessions"; const value = new URLSearchParams(location.search).get("view"); return value === "inbox" || value === "launch" || value === "apps" || value === "settings" ? value : "sessions"; }); const [selectedWorkspaceId, setSelectedWorkspaceId] = useState<string | null>(() => { if (typeof window === "undefined") return null; const query = new URLSearchParams(location.search); return query.has("action") || (!query.has("workspace") && query.has("repo") && query.has("file")) ? null : query.get("workspace"); }); const [selectedTerminalId, setSelectedTerminalId] = useState<string | null>(() => typeof window === "undefined" ? null : new URLSearchParams(location.search).get("surface")); const [detailTab, setDetailTab] = useState<DetailTab>(() => { if (typeof window === "undefined") return "terminal"; const tab = new URLSearchParams(location.search).get("tab"); return tab === "changes" || tab === "tasks" ? tab : "terminal"; });
  const [terminalView, setTerminalView] = useState<TerminalView | null>(null); const [screenError, setScreenError] = useState(""); const [draft, setDraft] = useState(""); const [sending, setSending] = useState(false); const [live, setLive] = useState(false); const [notice, setNotice] = useState("");
  const [actionId, setActionId] = useState<string | null>(() => typeof window === "undefined" ? null : new URLSearchParams(location.search).get("action"));
  const [focusedPreviewId, setFocusedPreviewId] = useState<string | null>(() => typeof window === "undefined" ? null : new URLSearchParams(location.search).get("preview"));
  const [documentTarget, setDocumentTarget] = useState<{ repoId: string; path: string } | null>(() => { if (typeof window === "undefined") return null; const query = new URLSearchParams(location.search); const repoId = query.get("repo"); const path = query.get("file"); return repoId && path && !query.has("workspace") && !query.has("action") ? { repoId, path } : null; });
  const [notificationContext, setNotificationContext] = useState<{ kind: string; file?: string | null } | null>(() => { if (typeof window === "undefined") return null; const query = new URLSearchParams(location.search); const kind = query.get("context"); return kind && query.has("workspace") ? { kind, file: query.get("file") } : null; });
  const [attachments, setAttachments] = useState<ImageAttachment[]>([]);
  const [queueItems, setQueueItems] = useState<PromptQueueItem[]>([]);
  const [homeMode, setHomeMode] = useState<HomeMode>(() => { if (typeof window === "undefined") return "sessions"; const query = new URLSearchParams(location.search).get("mode"); if (query === "worktrees") return "worktrees"; return localStorage.getItem("cmux-companion-home-mode") === "worktrees" ? "worktrees" : "sessions"; });
  const [readOnly, setReadOnly] = useState(() => typeof window === "undefined" || localStorage.getItem("cmux-companion-read-only") !== "false");
  const [installPrompt, setInstallPrompt] = useState<(Event & { prompt?: () => Promise<void> }) | null>(null); const refreshTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const detectedUrls = useRef(new Set<string>());

  const selectedWorkspace = useMemo(() => bootstrap?.workspaces.find((workspace) => workspace.id === selectedWorkspaceId) || null, [bootstrap, selectedWorkspaceId]);
  const selectedTerminal = selectedWorkspace?.terminals.find((terminal) => terminal.id === selectedTerminalId) || selectedWorkspace?.terminals[0] || null;
  const selectedRepo = useMemo(() => { const directory = selectedWorkspace?.current_directory || selectedTerminal?.current_directory; if (!directory) return null; return repos.find((repo) => directory === repo.path || directory.startsWith(`${repo.path}/`)) || null; }, [repos, selectedTerminal, selectedWorkspace]);
  const queueWorkspaceId = selectedWorkspace?.id || null; const queueSurfaceId = selectedTerminal?.id || null;

  const loadBootstrap = useCallback(async () => { try { const data = await api<Bootstrap>("/api/bootstrap"); setBootstrap(data); setAuth("paired"); return data; } catch (error) { if (error instanceof Error && error.message.includes("Pair")) setAuth("unpaired"); setBootstrap((current) => current ? { ...current, connected: false, error: "Waiting for cmux" } : null); return null; } }, []);
  const loadInbox = useCallback(async () => { try { setInbox(await api<Inbox>("/api/inbox")); } catch { /* cmux reconnects independently */ } }, []);
  const loadRepos = useCallback(async () => { try { setRepos((await api<{ repos: Repo[] }>("/api/repos")).repos); } catch { /* retry later */ } }, []);
  const loadPromptQueue = useCallback(async () => { if (!queueWorkspaceId || !queueSurfaceId) { setQueueItems([]); return; } try { const query = new URLSearchParams({ workspaceId: queueWorkspaceId, surfaceId: queueSurfaceId }); setQueueItems((await api<{ items: PromptQueueItem[] }>(`/api/prompt-queue?${query}`)).items); } catch { /* queue reconnects with the service */ } }, [queueSurfaceId, queueWorkspaceId]);

  useEffect(() => {
    if ("serviceWorker" in navigator) navigator.serviceWorker.register("/sw.js").catch(() => {});
    const onInstall = (event: Event) => { event.preventDefault(); setInstallPrompt(event as Event & { prompt?: () => Promise<void> }); };
    window.addEventListener("beforeinstallprompt", onInstall);
    api<{ paired: boolean }>("/api/auth/status").then((status) => setAuth(status.paired ? "paired" : "unpaired")).catch(() => setAuth("offline"));
    return () => window.removeEventListener("beforeinstallprompt", onInstall);
  }, []);

  useEffect(() => {
    if (auth !== "paired") return;
    let stopped = false; let socket: WebSocket | null = null; let retry: ReturnType<typeof setTimeout> | null = null; let attempt = 0;
    const refresh = () => { loadBootstrap(); loadInbox(); loadPromptQueue(); };
    const connect = () => { if (stopped) return; const protocol = location.protocol === "https:" ? "wss:" : "ws:"; socket = new WebSocket(`${protocol}//${location.host}/api/events`); socket.onopen = () => { attempt = 0; setLive(true); }; socket.onmessage = (message) => { try { const event = JSON.parse(message.data); if (event.type === "queue:changed") loadPromptQueue(); if (event.type === "cmux:event") { if (refreshTimer.current) clearTimeout(refreshTimer.current); refreshTimer.current = setTimeout(refresh, 300); } } catch { /* malformed event */ } }; socket.onclose = () => { setLive(false); if (!stopped) retry = setTimeout(connect, Math.min(30_000, 800 * (2 ** attempt++))); }; };
    const kickoff = setTimeout(() => { refresh(); loadRepos(); connect(); }, 0); const poll = setInterval(() => { if (document.visibilityState === "visible") refresh(); }, 8_000);
    return () => { stopped = true; clearTimeout(kickoff); clearInterval(poll); if (retry) clearTimeout(retry); if (refreshTimer.current) clearTimeout(refreshTimer.current); socket?.close(); };
  }, [auth, loadBootstrap, loadInbox, loadPromptQueue, loadRepos]);

  const loadTerminal = useCallback(async () => { if (!selectedTerminal) return; try { const result = await api<TerminalView>(`/api/terminals/${selectedTerminal.id}/replay?scrollback=600`); setTerminalView((current) => terminalViewSignature(current) === terminalViewSignature(result) ? current : result); setScreenError(""); } catch (error) { setScreenError(error instanceof Error ? error.message : "Unable to read this terminal"); } }, [selectedTerminal]);
  useEffect(() => { if (!selectedTerminal || detailTab !== "terminal") return; const kickoff = setTimeout(loadTerminal, 0); const poll = setInterval(() => { if (document.visibilityState === "visible") loadTerminal(); }, 1_500); return () => { clearTimeout(kickoff); clearInterval(poll); }; }, [selectedTerminal, detailTab, loadTerminal]);
  useEffect(() => { const timer = setTimeout(loadPromptQueue, 0); return () => clearTimeout(timer); }, [loadPromptQueue]);

  const discoverLocalUrl = useCallback(async (url: string, open = false) => {
    const port = localUrlPort(url); if (!port || !selectedWorkspace) return;
    try {
      const result = await api<{ preview: { id: string }; created: boolean }>("/api/previews/discover", { method: "POST", body: JSON.stringify({ workspaceId: selectedWorkspace.id, repoId: selectedRepo?.id || null, port, url }) });
      if (result.created) setNotice(`Local app detected on port ${port}`);
      if (open) { setFocusedPreviewId(result.preview.id); setSelectedWorkspaceId(null); setView("apps"); history.replaceState(null, "", `/?view=apps&preview=${encodeURIComponent(result.preview.id)}`); }
    } catch (error) { if (open) setNotice(error instanceof Error ? error.message : "Could not register local app"); }
  }, [selectedRepo?.id, selectedWorkspace]);
  useEffect(() => {
    if (!terminalView || !selectedWorkspace) return;
    for (const url of terminalContext(terminalView).urls) {
      const key = `${selectedWorkspace.id}:${url}`; if (detectedUrls.current.has(key)) continue;
      detectedUrls.current.add(key); discoverLocalUrl(url).catch(() => {});
    }
  }, [terminalView, selectedWorkspace, discoverLocalUrl]);

  async function pair(event: FormEvent) { event.preventDefault(); setPairingError(""); try { await api("/api/auth/pair", { method: "POST", body: JSON.stringify({ token: pairingToken.trim() }) }); setPairingToken(""); setAuth("paired"); } catch (error) { setPairingError(error instanceof Error ? error.message : "Pairing failed"); } }
  function openWorkspace(workspace: Workspace, tab: DetailTab = "terminal") { setDocumentTarget(null); setActionId(null); setNotificationContext(null); setSelectedWorkspaceId(workspace.id); setSelectedTerminalId(workspace.terminals.find((terminal) => terminal.is_focused)?.id || workspace.terminals[0]?.id || null); setTerminalView(null); clearAttachments(); setDetailTab(tab); history.replaceState(null, "", `/?workspace=${encodeURIComponent(workspace.id)}${tab !== "terminal" ? `&tab=${tab}` : ""}`); }
  function closeWorkspaceView() { setSelectedWorkspaceId(null); setSelectedTerminalId(null); setTerminalView(null); clearAttachments(); history.replaceState(null, "", `/?view=${view}`); }
  function clearAttachments() { setAttachments((current) => { current.forEach((image) => URL.revokeObjectURL(image.preview)); return []; }); }
  async function addImage(file: File) { if (attachments.length >= 4) { setNotice("You can attach up to four images at a time"); return; } if (!file.type.startsWith("image/")) { setNotice("Choose an image file"); return; } if (file.size > 8 * 1024 * 1024) { setNotice("Image must be 8 MB or smaller"); return; } try { const dataUrl = await imageDataUrl(file); const result = await api<{ image: Omit<ImageAttachment, "preview"> }>("/api/attachments/images", { method: "POST", body: JSON.stringify({ dataUrl, name: file.name || "pasted image" }) }); const attached = { ...result.image, preview: URL.createObjectURL(file) }; setAttachments((current) => { if (current.length >= 4) { URL.revokeObjectURL(attached.preview); return current; } return [...current, attached]; }); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not attach image"); } }
  function removeImage(path: string) { setAttachments((current) => current.filter((image) => { if (image.path === path) URL.revokeObjectURL(image.preview); return image.path !== path; })); }
  async function sendPrompt(event: FormEvent) { event.preventDefault(); if (!selectedTerminal || (!draft.trim() && attachments.length === 0) || readOnly) return; const text = composedPrompt(draft, attachments); setSending(true); try { await api(`/api/terminals/${selectedTerminal.id}/input`, { method: "POST", body: JSON.stringify({ text, enter: true }) }); setDraft(""); clearAttachments(); setTimeout(loadTerminal, 200); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not send input"); } finally { setSending(false); } }
  async function queuePrompt() { if (!selectedWorkspace || !selectedTerminal || (!draft.trim() && attachments.length === 0) || readOnly) return; const text = composedPrompt(draft, attachments); setSending(true); try { await api("/api/prompt-queue", { method: "POST", body: JSON.stringify({ workspaceId: selectedWorkspace.id, surfaceId: selectedTerminal.id, text }) }); setDraft(""); clearAttachments(); await loadPromptQueue(); setNotice("Prompt queued for the next agent stop"); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not queue prompt"); } finally { setSending(false); } }
  async function queueAction(id: string, action: "update" | "move" | "send" | "remove", value?: string | number) { setSending(true); try { const path = action === "update" || action === "remove" ? `/api/prompt-queue/${id}` : `/api/prompt-queue/${id}/${action}`; const method = action === "update" ? "PATCH" : action === "remove" ? "DELETE" : "POST"; const body = action === "update" ? JSON.stringify({ text: value }) : action === "move" ? JSON.stringify({ direction: value }) : "{}"; await api(path, { method, body }); await loadPromptQueue(); if (action === "send") { setNotice("Queued prompt sent"); setTimeout(loadTerminal, 200); } } catch (error) { setNotice(error instanceof Error ? error.message : "Queue action failed"); } finally { setSending(false); } }
  async function fixPreview(preview: Preview, prompt: string, queue: boolean) { const workspace = bootstrap?.workspaces.find((item) => item.id === preview.workspaceId); const terminal = workspace?.terminals.find((item) => item.is_focused) || workspace?.terminals[0]; if (!workspace || !terminal) throw new Error("That cmux session is no longer open"); if (queue) await api("/api/prompt-queue", { method: "POST", body: JSON.stringify({ workspaceId: workspace.id, surfaceId: terminal.id, text: prompt }) }); else await api(`/api/terminals/${terminal.id}/input`, { method: "POST", body: JSON.stringify({ text: prompt, enter: true }) }); if (selectedWorkspace?.id === workspace.id) await loadPromptQueue(); setNotice(queue ? "Visual fix queued for the agent" : "Visual fix sent to the agent"); }
  async function sendKey(key: string) { if (!selectedTerminal || readOnly) return; setSending(true); try { await api(`/api/terminals/${selectedTerminal.id}/key`, { method: "POST", body: JSON.stringify({ key }) }); setTimeout(loadTerminal, 150); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not send key"); } finally { setSending(false); } }
  function changeReadOnly(value: boolean) { setReadOnly(value); localStorage.setItem("cmux-companion-read-only", String(value)); }
  function changeHomeMode(mode: HomeMode) { setHomeMode(mode); localStorage.setItem("cmux-companion-home-mode", mode); history.replaceState(null, "", `/?view=sessions${mode === "worktrees" ? "&mode=worktrees" : ""}`); }
  function changeView(next: View) { setSelectedWorkspaceId(null); setDocumentTarget(null); setActionId(null); setView(next); history.replaceState(null, "", `/?view=${next}`); }
  function openDocument(repoId: string, path: string) { setDocumentTarget({ repoId, path: path.replace(/^\.\//, "") }); history.replaceState(null, "", `/?repo=${encodeURIComponent(repoId)}&file=${encodeURIComponent(path.replace(/^\.\//, ""))}`); }
  function openRepoWorkspace(repoId: string) { const repo = repos.find((item) => item.id === repoId); const workspace = bootstrap?.workspaces.find((item) => repo && (item.current_directory === repo.path || item.current_directory?.startsWith(`${repo.path}/`))); if (workspace) openWorkspace(workspace); else setNotice("No open cmux session uses this repository"); }

  if (auth === "loading") return <LoadingScreen />;
  if (auth === "unpaired" || auth === "offline") return <PairScreen offline={auth === "offline"} token={pairingToken} error={pairingError} onToken={setPairingToken} onPair={pair} />;
  if (documentTarget) return <MarkdownViewer repoId={documentTarget.repoId} path={documentTarget.path} onClose={() => { setDocumentTarget(null); history.replaceState(null, "", selectedWorkspace ? `/?workspace=${encodeURIComponent(selectedWorkspace.id)}` : "/?view=sessions"); }} onAsk={(file) => { const workspace = bootstrap?.workspaces.find((item) => item.current_directory === file.repo.path || item.current_directory?.startsWith(`${file.repo.path}/`)); if (!workspace) { setNotice("Open a session for this repository first"); return; } setDraft(`Please review ${file.path} and help me with it.`); openWorkspace(workspace); }} onOpenWorkspace={openRepoWorkspace} />;
  if (selectedWorkspace && selectedTerminal) return <WorkspaceDetail workspace={selectedWorkspace} terminal={selectedTerminal} repo={selectedRepo} tab={detailTab} context={notificationContext} terminalView={terminalView} screenError={screenError} draft={draft} attachments={attachments} queueItems={queueItems} sending={sending} readOnly={readOnly} onBack={closeWorkspaceView} onTab={setDetailTab} onTerminal={(id) => { setSelectedTerminalId(id); setTerminalView(null); clearAttachments(); }} onDraft={setDraft} onImage={addImage} onRemoveImage={removeImage} onSubmit={sendPrompt} onQueue={queuePrompt} onQueueUpdate={(id, text) => queueAction(id, "update", text)} onQueueMove={(id, direction) => queueAction(id, "move", direction)} onQueueSend={(id) => queueAction(id, "send")} onQueueRemove={(id) => queueAction(id, "remove")} onKey={sendKey} onReadOnly={() => changeReadOnly(!readOnly)} onRefresh={loadTerminal} onChanged={async () => { await loadBootstrap(); }} onNotice={setNotice} onDismissContext={() => setNotificationContext(null)} onMarkdown={(path) => selectedRepo ? openDocument(selectedRepo.id, path) : setNotice("That file is outside a catalogued repository")} onLocalUrl={(url) => discoverLocalUrl(url, true)} onApps={() => changeView("apps")} />;

  return <main className="app-shell"><AppHeader connected={Boolean(bootstrap?.connected)} live={live} device={bootstrap?.host?.mac_display_name || "Your Mac"} />{notice && <button className="toast" onClick={() => setNotice("")}>{notice}<span>×</span></button>}
    {view === "sessions" && <><HomeModeSwitch mode={homeMode} onMode={changeHomeMode} />{homeMode === "sessions" ? <SessionsView bootstrap={bootstrap} onOpen={openWorkspace} onLaunch={() => changeView("launch")} onRefresh={loadBootstrap} /> : <WorktreeDashboardView onOpenWorkspace={(id) => { const workspace = bootstrap?.workspaces.find((item) => item.id === id); if (workspace) openWorkspace(workspace); else setNotice("That cmux session is no longer open"); }} onLaunched={async (id) => { for (let attempt = 0; attempt < 12; attempt += 1) { const data = await loadBootstrap(); const workspace = data?.workspaces.find((item) => item.id === id); if (workspace) { openWorkspace(workspace); return; } await new Promise((resolve) => setTimeout(resolve, 250)); } setNotice("Agent launched. Its session will appear shortly."); }} onNotice={setNotice} />}</>}
    {view === "inbox" && <InboxView inbox={inbox} workspaces={bootstrap?.workspaces || []} repos={repos} focusedId={actionId} onCloseFocus={() => { setActionId(null); history.replaceState(null, "", "/?view=inbox"); }} onDocument={openDocument} onReload={loadInbox} onOpen={(id) => { const workspace = bootstrap?.workspaces.find((item) => item.id === id); if (workspace) openWorkspace(workspace); }} onNotice={setNotice} />}
    {view === "launch" && <LaunchView repos={repos} onReload={loadRepos} onLaunched={async (id) => { const data = await loadBootstrap(); const workspace = data?.workspaces.find((item) => item.id === id); if (workspace) openWorkspace(workspace); else { setView("sessions"); setNotice("Workspace launched. It will appear in a moment."); } }} />}
    {view === "apps" && <AppsView focusedId={focusedPreviewId} onOpenWorkspace={(id) => { const workspace = bootstrap?.workspaces.find((item) => item.id === id); if (workspace) openWorkspace(workspace); else setNotice("That cmux session is no longer open"); }} onNotice={setNotice} onFix={fixPreview} />}
    {view === "settings" && <SettingsView bootstrap={bootstrap} readOnly={readOnly} installable={Boolean(installPrompt)} onReadOnly={changeReadOnly} onInstall={() => installPrompt?.prompt?.()} onApps={() => changeView("apps")} onNotice={setNotice} onLogout={async () => { await api("/api/auth/logout", { method: "POST", body: "{}" }); setAuth("unpaired"); }} />}
    <BottomNav view={view} onView={changeView} attention={inbox.actionableCount + inbox.unreadCount} /></main>;
}

function AppHeader({ connected, live, device }: { connected: boolean; live: boolean; device: string }) { return <header className="topbar"><div className="brand-mark">c</div><div className="brand-copy"><strong>cmux companion</strong><span><i className={`connection-dot ${connected ? "" : "offline"}`} />{connected ? device : "Waiting for cmux"}</span></div><span className={`live-badge ${live ? "" : "sync"}`}>{live ? "LIVE" : "SYNC"}</span></header>; }

export function HomeModeSwitch({ mode, onMode }: { mode: HomeMode; onMode: (mode: HomeMode) => void }) { return <nav className="home-mode-switch" aria-label="Home visualization"><button className={mode === "sessions" ? "active" : ""} aria-pressed={mode === "sessions"} onClick={() => onMode("sessions")}>Sessions</button><button className={mode === "worktrees" ? "active" : ""} aria-pressed={mode === "worktrees"} onClick={() => onMode("worktrees")}>Worktrees <b>Beta</b></button></nav>; }

function SessionsView({ bootstrap, onOpen, onLaunch, onRefresh }: { bootstrap: Bootstrap | null; onOpen: (workspace: Workspace) => void; onLaunch: () => void; onRefresh: () => void }) {
  const workspaces = bootstrap?.workspaces || []; const needsYou = workspaces.filter((item) => sessionState(item).tone === "attention").length; const working = workspaces.filter((item) => sessionState(item).tone === "working").length;
  return <><section className="hero"><p className="eyebrow">PRIVATE · TAILSCALE</p><h1>{needsYou ? `${needsYou} session${needsYou > 1 ? "s" : ""} need you.` : working ? "Your agents are moving." : "Ready when you are."}</h1><p>Review, unblock, and launch coding work from anywhere on your private network.</p><div className="summary-row"><div><strong>{workspaces.length}</strong><span>sessions</span></div><div><strong className="accent-number">{needsYou}</strong><span>needs you</span></div><div><strong>{working}</strong><span>working</span></div></div></section><section className="content-section"><div className="section-heading"><h2>Sessions</h2><div><button className="text-button" onClick={onRefresh}>Refresh</button><button className="primary-small" onClick={onLaunch}>＋ New</button></div></div>{!bootstrap && <WorkspaceSkeleton />}{bootstrap && workspaces.length === 0 && <Empty icon="⌁" title="No sessions yet" body="Launch a repository here or open a workspace on your Mac." action={<button className="primary-button" onClick={onLaunch}>Launch a workspace</button>} />}<div className="workspace-list">{workspaces.map((workspace) => { const state = sessionState(workspace); const terminal = workspace.terminals.find((item) => item.is_focused) || workspace.terminals[0]; return <button className="workspace-card" key={workspace.id} onClick={() => onOpen(workspace)}><div className="workspace-card-head"><span className={`status-orb ${state.tone}`} /><div><strong>{workspace.title || "Untitled workspace"}</strong><span>{compactPath(workspace.current_directory || terminal?.current_directory)}</span></div><time>{relativeTime(workspace.last_activity_at)}</time></div><p>{workspace.preview || terminal?.title || "Terminal ready"}</p><div className="card-foot"><span className={`state-pill ${state.tone}`}>{state.label}</span><span>{workspace.terminals.length} terminal{workspace.terminals.length === 1 ? "" : "s"}</span><b>Open ›</b></div></button>; })}</div></section></>;
}

export function InboxView({ inbox, workspaces, repos, focusedId, onCloseFocus, onDocument, onReload, onOpen, onNotice }: { inbox: Inbox; workspaces: Workspace[]; repos: Repo[]; focusedId: string | null; onCloseFocus: () => void; onDocument: (repoId: string, path: string) => void; onReload: () => void; onOpen: (id: string) => void; onNotice: (message: string) => void }) {
  const [busy, setBusy] = useState("");
  async function reply(item: InboxItem, body: Record<string, unknown>) {
    if (item.kind === "question" && Array.isArray(body.selections) && body.selections[0] === "Write reply…") {
      const answer = window.prompt("Reply to the agent");
      if (!answer?.trim()) return;
      body = { selections: [answer.trim()] };
    }
    if (item.kind === "exitPlan" && body.mode === "deny") {
      body = { ...body, feedback: window.prompt("Optional feedback for the agent")?.trim() || "" };
    }
    setBusy(item.id);
    try { await api(`/api/inbox/${item.requestId}/reply`, { method: "POST", body: JSON.stringify({ kind: item.kind, ...body }) }); await onReload(); if (focusedId === item.id) onCloseFocus(); }
    catch (error) { onNotice(error instanceof Error ? error.message : "Could not reply"); }
    finally { setBusy(""); }
  }
  async function markRead(item: InboxItem) { setBusy(item.id); try { await api(`/api/notifications/${item.id}/read`, { method: "POST", body: "{}" }); await onReload(); if (focusedId === item.id) onCloseFocus(); } catch (error) { onNotice(error instanceof Error ? error.message : "Could not mark as read"); } finally { setBusy(""); } }
  const visible = focusedId ? inbox.items.filter((item) => item.id === focusedId) : inbox.items;
  function card(item: InboxItem) {
    const workspace = workspaces.find((value) => value.id === item.workspaceId);
    const directory = workspace?.current_directory || workspace?.terminals[0]?.current_directory;
    const repo = repos.find((value) => directory && (directory === value.path || directory.startsWith(`${value.path}/`)));
    const markdown = contextMarkdown(item);
    return <article className={`inbox-card${focusedId ? " focused-action-card" : ""}`} key={item.id}><div className="inbox-head"><span className={`inbox-kind ${item.kind}`}>{item.kind === "permissionRequest" ? "Permission" : item.kind === "question" ? "Question" : item.kind === "exitPlan" ? "Plan" : "Update"}</span>{item.workspaceId && <button onClick={() => onOpen(item.workspaceId!)}>{workspace?.title || "Open session"} ›</button>}</div><h2>{item.title}</h2>{item.subtitle && <p className="muted">{item.subtitle}</p>}{item.body && <p>{item.body}</p>}{item.toolName && <div className="tool-preview"><strong>{item.toolName}</strong>{item.toolInput !== null && item.toolInput !== undefined && <pre>{typeof item.toolInput === "string" ? item.toolInput : JSON.stringify(item.toolInput, null, 2)}</pre>}</div>}{markdown.length > 0 && <div className="context-file-row">{markdown.map((path) => <button disabled={!repo} onClick={() => repo && onDocument(repo.id, path)} key={path}>◇ {path.split("/").pop()}</button>)}</div>}<div className="action-row">{item.kind === "permissionRequest" && <><button className="approve" disabled={busy === item.id} onClick={() => reply(item, { mode: "once" })}>Approve once</button><button className="deny" disabled={busy === item.id} onClick={() => reply(item, { mode: "deny" })}>Deny</button></>}{item.kind === "question" && questionLabels(item).map((label) => <button className="approve" disabled={busy === item.id} key={label} onClick={() => reply(item, { selections: [label] })}>{label}</button>)}{item.kind === "exitPlan" && <><button className="approve" disabled={busy === item.id} onClick={() => reply(item, { mode: "manual" })}>Approve</button><button disabled={busy === item.id} onClick={() => reply(item, { mode: "autoAccept" })}>Auto accept</button><button className="deny" disabled={busy === item.id} onClick={() => reply(item, { mode: "deny" })}>Deny</button></>}{item.type === "notification" && <button disabled={busy === item.id} onClick={() => markRead(item)}>Mark read</button>}</div></article>;
  }
  return <section className={`subpage${focusedId ? " action-focus-page" : ""}`}><div className="page-kicker"><div><p className="eyebrow">{focusedId ? "NEEDS YOUR DECISION" : "ACTION QUEUE"}</p><h1>{focusedId ? "Session action" : "Inbox"}</h1></div>{focusedId ? <button className="text-button" onClick={onCloseFocus}>All actions</button> : <button className="text-button" onClick={onReload}>Refresh</button>}</div><p className="subpage-intro">{focusedId ? "Review the exact request, respond, or open its session for more context." : "Only decisions and meaningful agent notifications—no tool-call noise."}</p>{visible.length === 0 && <Empty icon="✓" title={focusedId ? "Action already resolved" : "All clear"} body={focusedId ? "This request is no longer pending. It may have been handled on your Mac." : "Your agents are not waiting on anything."} action={focusedId ? <button className="primary-button" onClick={onCloseFocus}>Open inbox</button> : undefined} />}<div className="inbox-list">{visible.map(card)}</div></section>;
}
function questionLabels(item: InboxItem) { const labels = (item.questionOptions || []).map((option) => typeof option === "string" ? option : option.label || option.value || "").filter(Boolean).slice(0, 8); return labels.length ? labels : ["Write reply…"]; }
function contextMarkdown(item: InboxItem) { return splitContextLinks(JSON.stringify(item)).filter((part: { type: string }) => part.type === "markdown").map((part: { text: string }) => part.text).filter((value: string, index: number, all: string[]) => all.indexOf(value) === index).slice(0, 6); }

function LaunchView({ repos, onReload, onLaunched }: { repos: Repo[]; onReload: () => void; onLaunched: (id: string) => void }) {
  const [query, setQuery] = useState(""); const [selected, setSelected] = useState<Repo | null>(null); const [agent, setAgent] = useState("codex"); const [prompt, setPrompt] = useState(""); const [script, setScript] = useState(""); const [title, setTitle] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const filtered = repos.filter((repo) => `${repo.name} ${repo.root} ${repo.branch}`.toLowerCase().includes(query.toLowerCase())).slice(0, 40);
  async function launch(event: FormEvent) { event.preventDefault(); if (!selected) return; setBusy(true); setError(""); try { const result = await api<{ workspace: { workspace_id: string } }>("/api/workspaces", { method: "POST", body: JSON.stringify({ repoId: selected.id, title: title || selected.name, agent: script ? "shell" : agent, prompt, script: script || null }) }); onLaunched(result.workspace.workspace_id); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not launch workspace"); } finally { setBusy(false); } }
  return <section className="subpage launch-page"><div className="page-kicker"><div><p className="eyebrow">REPO LAUNCHPAD</p><h1>Start work</h1></div><button className="text-button" onClick={onReload}>Rescan</button></div><p className="subpage-intro">Open an approved local repository directly in a fresh cmux workspace.</p>{!selected ? <><label className="search-box"><span>⌕</span><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Find a repository…" autoFocus /></label><div className="repo-list">{filtered.map((repo) => <button key={repo.id} onClick={() => { setSelected(repo); setTitle(repo.name); }}><span className="repo-icon">{repo.name.slice(0, 1).toUpperCase()}</span><div><strong>{repo.name}</strong><span>{repo.root} · {repo.branch}</span></div>{repo.dirty && <em>{repo.changedFiles} changed</em>}<b>›</b></button>)}</div></> : <form className="launch-form" onSubmit={launch}><button type="button" className="inline-back" onClick={() => setSelected(null)}>‹ Choose another repo</button><div className="selected-repo"><span className="repo-icon">{selected.name.slice(0, 1).toUpperCase()}</span><div><strong>{selected.name}</strong><span>{compactPath(selected.path)} · {selected.branch}</span></div></div><label>Workspace name<input value={title} onChange={(event) => setTitle(event.target.value)} maxLength={100} /></label><fieldset><legend>Start with</legend>{["codex", "claude", "shell"].map((value) => <button type="button" className={agent === value && !script ? "selected" : ""} onClick={() => { setAgent(value); setScript(""); }} key={value}>{value === "codex" ? "Codex" : value === "claude" ? "Claude" : "Shell"}</button>)}</fieldset>{selected.scripts.length > 0 && <label>Or run package script<select value={script} onChange={(event) => setScript(event.target.value)}><option value="">No script</option>{selected.scripts.map((value) => <option key={value} value={value}>npm run {value}</option>)}</select></label>}{!script && agent !== "shell" && <label>Initial task<textarea rows={5} value={prompt} onChange={(event) => setPrompt(event.target.value)} maxLength={8000} placeholder="Describe the outcome you want…" /></label>}{error && <p className="form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy ? "Launching…" : `Launch ${script ? "script" : agent}`}</button></form>}</section>;
}

function WorkspaceDetail(props: { workspace: Workspace; terminal: Terminal; repo: Repo | null; tab: DetailTab; context: { kind: string; file?: string | null } | null; terminalView: TerminalView | null; screenError: string; draft: string; attachments: ImageAttachment[]; queueItems: PromptQueueItem[]; sending: boolean; readOnly: boolean; onBack: () => void; onTab: (tab: DetailTab) => void; onTerminal: (id: string) => void; onDraft: (value: string) => void; onImage: (file: File) => void; onRemoveImage: (path: string) => void; onSubmit: (event: FormEvent) => void; onQueue: () => void; onQueueUpdate: (id: string, text: string) => Promise<void>; onQueueMove: (id: string, direction: number) => Promise<void>; onQueueSend: (id: string) => Promise<void>; onQueueRemove: (id: string) => Promise<void>; onKey: (key: string) => void; onReadOnly: () => void; onRefresh: () => void; onChanged: () => void; onNotice: (message: string) => void; onDismissContext: () => void; onMarkdown: (path: string) => void; onLocalUrl: (url: string) => void; onApps: () => void }) {
  const [menuOpen, setMenuOpen] = useState(false);
  const [shortcutsOpen, setShortcutsOpen] = useState(false);
  const [fontSize, setFontSize] = useState(() => typeof window === "undefined" ? 14 : Number(localStorage.getItem("cmux-companion-terminal-font")) || 14);
  const [fitToPhone, setFitToPhone] = useState(() => typeof window === "undefined" || localStorage.getItem("cmux-companion-fit-terminal") !== "false");
  function changeFont(delta: number) { setFontSize((current) => { const next = Math.max(11, Math.min(20, current + delta)); localStorage.setItem("cmux-companion-terminal-font", String(next)); return next; }); }
  function toggleFit() { setFitToPhone((current) => { const next = !current; localStorage.setItem("cmux-companion-fit-terminal", String(next)); return next; }); }
  return (
    <main className="detail-shell">
      <header className="detail-header"><button className="back-button" onClick={props.onBack}>‹ <span>Back</span></button><div><strong>{props.workspace.title}</strong><span>{compactPath(props.workspace.current_directory)}</span></div><button className="session-menu-button" aria-label="Session menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(true)}><span className={`status-orb ${sessionState(props.workspace).tone}`} />•••</button></header>
      {props.context && <aside className={`notification-context ${props.context.kind}`}><div><strong>{props.context.kind === "failure" ? "A command or test failed" : props.context.kind === "pullRequest" ? "Pull request updated" : props.context.kind === "completion" ? "Work is ready to review" : "Session update"}</strong><span>You opened this session from a notification.</span></div>{props.context.file && <button onClick={() => props.onMarkdown(props.context!.file!)}>Open {props.context.file.split("/").pop()}</button>}<button aria-label="Dismiss notification context" onClick={props.onDismissContext}>×</button></aside>}
      {props.tab === "terminal" && <TerminalPanel {...props} fontSize={fontSize} fitToPhone={fitToPhone} shortcutsOpen={shortcutsOpen} onShortcuts={setShortcutsOpen} />}
      {props.tab === "tasks" && <HealthPanel workspace={props.workspace} terminal={props.terminal} onChanged={props.onChanged} onNotice={props.onNotice} />}
      {props.tab === "changes" && <ChangesPanel repo={props.repo} onMarkdown={props.onMarkdown} />}
      {menuOpen && <><button className="session-menu-backdrop" aria-label="Close session menu" onClick={() => setMenuOpen(false)} /><section className="session-menu" role="dialog" aria-modal="true" aria-label="Session menu"><header><div><strong>{props.workspace.title}</strong><span>Session controls</span></div><button onClick={() => setMenuOpen(false)}>×</button></header><nav className="session-menu-nav">{(["terminal", "tasks", "changes"] as DetailTab[]).map((tab) => <button className={props.tab === tab ? "active" : ""} onClick={() => { props.onTab(tab); setMenuOpen(false); }} key={tab}>{tab === "tasks" ? "Health" : tab[0].toUpperCase() + tab.slice(1)}</button>)}</nav><PullRequestBanner repo={props.repo} />{props.workspace.terminals.length > 1 && <div className="session-menu-section"><span>Terminals</span><div className="menu-terminal-list">{props.workspace.terminals.map((terminal, index) => <button className={terminal.id === props.terminal.id ? "active" : ""} onClick={() => { props.onTerminal(terminal.id); setMenuOpen(false); }} key={terminal.id}>{index + 1}. {terminal.title}</button>)}</div></div>}<div className="session-menu-section"><span>Display & input</span><div className="menu-action-grid"><button className={fitToPhone ? "active" : ""} onClick={toggleFit}>Fit text <b>{fitToPhone ? "On" : "Off"}</b></button><button onClick={props.onRefresh}>Refresh</button><button onClick={() => changeFont(-1)} disabled={fontSize <= 11}>Text A−</button><button onClick={() => changeFont(1)} disabled={fontSize >= 20}>Text A＋</button><button className={!props.readOnly ? "active" : ""} onClick={props.onReadOnly}>{props.readOnly ? "Enable input" : "Input enabled"}</button><button disabled={props.readOnly} onClick={() => { props.onTab("terminal"); setShortcutsOpen(true); setMenuOpen(false); }}>／ Shortcuts</button><button onClick={() => { setMenuOpen(false); props.onApps(); }}>Local apps <b>›</b></button></div></div><div className="session-menu-section"><span>Special keys</span><div className="menu-key-grid">{[["Esc", "escape"], ["Tab", "tab"], ["↑", "up"], ["↓", "down"], ["Ctrl-C", "ctrl+c"], ["Enter", "enter"]].map(([label, key]) => <button disabled={props.readOnly || props.sending} onClick={() => props.onKey(key)} key={key}>{label}</button>)}</div></div></section></>}
    </main>
  );
}

export function PullRequestBanner({ repo }: { repo: Repo | null }) {
  const [pullRequest, setPullRequest] = useState<PullRequest | null>(null);
  useEffect(() => {
    if (!repo) return;
    let active = true;
    const timer = setTimeout(() => {
      api<{ pullRequest: PullRequest | null }>(`/api/repos/${repo.id}/pull-request`)
        .then((result) => { if (active) setPullRequest(result.pullRequest); })
        .catch(() => {});
    }, 0);
    return () => { active = false; clearTimeout(timer); };
  }, [repo]);
  if (!pullRequest) return null;
  const review = pullRequest.isDraft ? "Draft" : pullRequest.reviewDecision === "APPROVED" ? "Approved" : pullRequest.reviewDecision === "CHANGES_REQUESTED" ? "Changes requested" : "Review needed";
  const checks = pullRequest.checks.failed ? `${pullRequest.checks.failed} failed` : pullRequest.checks.pending ? `${pullRequest.checks.pending} running` : pullRequest.checks.total ? `${pullRequest.checks.passed}/${pullRequest.checks.total} checks passed` : "No checks";
  const tone = pullRequest.checks.failed || pullRequest.reviewDecision === "CHANGES_REQUESTED" ? "problem" : pullRequest.checks.pending ? "pending" : "good";
  return <a className={`pr-banner ${tone}`} href={pullRequest.url} target="_blank" rel="noreferrer"><span className="pr-icon">PR</span><div><strong>#{pullRequest.number} {pullRequest.title}</strong><small>{pullRequest.headBranch} → {pullRequest.baseBranch}</small></div><span className="pr-state"><b>{review}</b><small>{checks}</small></span><em>↗</em></a>;
}

export function TerminalPanel(props: { workspace: Workspace; terminal: Terminal; terminalView: TerminalView | null; screenError: string; draft: string; attachments: ImageAttachment[]; queueItems: PromptQueueItem[]; sending: boolean; readOnly: boolean; fontSize: number; fitToPhone: boolean; shortcutsOpen: boolean; onTerminal: (id: string) => void; onDraft: (value: string) => void; onImage: (file: File) => void; onRemoveImage: (path: string) => void; onSubmit: (event: FormEvent) => void; onQueue: () => void; onQueueUpdate: (id: string, text: string) => Promise<void>; onQueueMove: (id: string, direction: number) => Promise<void>; onQueueSend: (id: string) => Promise<void>; onQueueRemove: (id: string) => Promise<void>; onKey: (key: string) => void; onReadOnly: () => void; onRefresh: () => void; onShortcuts: (open: boolean) => void; onMarkdown: (path: string) => void; onLocalUrl: (url: string) => void }) {
  const screenRef = useRef<HTMLDivElement>(null);
  const composerRef = useRef<HTMLTextAreaElement>(null);
  const imageInputRef = useRef<HTMLInputElement>(null);
  const initial = useRef(true);
  const following = useRef(true);
  const previous = useRef("empty");
  const [unseen, setUnseen] = useState(false);
  const [writingMode, setWritingMode] = useState(false);
  const [queueOpen, setQueueOpen] = useState(false);
  const matchingShortcuts = slashShortcuts(props.draft);
  const showShortcuts = !props.readOnly && (props.shortcutsOpen || props.draft.trimStart().startsWith("/"));
  const contentSignature = terminalViewSignature(props.terminalView);
  useEffect(() => { initial.current = true; following.current = true; previous.current = "empty"; }, [props.terminal.id]);
  useEffect(() => { const changed = contentSignature !== previous.current; previous.current = contentSignature; const next = nextFollowState({ initial: initial.current, following: following.current, contentChanged: changed }); if (next.scroll) requestAnimationFrame(() => { const element = screenRef.current; if (element) element.scrollTop = element.scrollHeight; }); if (next.unseen) setUnseen(true); else if (next.scroll) setUnseen(false); initial.current = false; }, [contentSignature]);
  useEffect(() => { const element = composerRef.current; if (!element || writingMode) return; element.style.height = "0px"; element.style.height = `${Math.min(element.scrollHeight, Math.max(120, window.innerHeight * 0.32))}px`; }, [props.draft, writingMode]);
  function jumpLatest() { const element = screenRef.current; if (element) element.scrollTop = element.scrollHeight; following.current = true; setUnseen(false); }
  function chooseShortcut(command: string) {
    props.onDraft(command);
    props.onShortcuts(false);
    requestAnimationFrame(() => composerRef.current?.focus());
  }
  return (
    <div className="terminal-panel">
      <section className="terminal-window">
        {props.screenError ? <div className="terminal-error">{props.screenError}</div> : <div className={`terminal-scroll${props.fitToPhone ? " fit-phone" : ""}`} ref={screenRef} style={{ "--terminal-font-size": `${props.fontSize}px` } as React.CSSProperties} onTouchStart={() => { following.current = false; }} onScroll={(event) => { const near = isNearBottom(event.currentTarget); following.current = near; if (near) setUnseen(false); }}><TerminalGrid view={props.terminalView} hideNativeComposer={props.fitToPhone} reflow={props.fitToPhone} onMarkdownLink={props.onMarkdown} onLocalUrl={props.onLocalUrl} /></div>}
        {unseen && <button className="jump-latest" onClick={jumpLatest}>↓ Jump to latest</button>}
      </section>
      <div className="terminal-controls">
        {showShortcuts && (
          <div className="shortcut-palette">
            <div className="shortcut-palette-head"><strong>Agent shortcuts</strong><span>Tap to insert · send when ready</span></div>
            {matchingShortcuts.length ? <div className="shortcut-list">{matchingShortcuts.map((shortcut) => (
              <button type="button" onClick={() => chooseShortcut(shortcut.command)} key={shortcut.command}>
                <code>{shortcut.command}</code><span>{shortcut.description}</span><small>{shortcut.agents.join(" · ")}</small>
              </button>
            ))}</div> : <p className="shortcut-empty">No matching shortcut. Use <button type="button" onClick={() => chooseShortcut("/help")}>/help</button> for the active agent&apos;s full list.</p>}
          </div>
        )}
        {props.attachments.length > 0 && <div className="attachment-strip">{props.attachments.map((image) => <div key={image.path}><img src={image.preview} alt={image.name} /><span>{image.name}</span><button type="button" aria-label={`Remove ${image.name}`} onClick={() => props.onRemoveImage(image.path)}>×</button></div>)}</div>}
        <form className="composer compact-composer" onSubmit={props.onSubmit}><input ref={imageInputRef} className="image-input" type="file" accept="image/png,image/jpeg,image/gif,image/webp" multiple onChange={(event) => { [...(event.currentTarget.files || [])].slice(0, 4 - props.attachments.length).forEach(props.onImage); event.currentTarget.value = ""; }} /><button type="button" className="attach-button" aria-label="Attach an image" disabled={props.readOnly || props.sending || props.attachments.length >= 4} onClick={() => imageInputRef.current?.click()}>＋</button><div className="composer-editor"><textarea ref={composerRef} aria-label="Terminal input" placeholder={props.readOnly ? "Use ••• to enable input" : "Message…"} value={props.draft} onChange={(event) => props.onDraft(event.target.value)} onPaste={(event) => { const images = [...event.clipboardData.items].filter((item) => item.type.startsWith("image/")).map((item) => item.getAsFile()).filter((file): file is File => Boolean(file)).slice(0, 4 - props.attachments.length); if (images.length) { event.preventDefault(); images.forEach(props.onImage); } }} disabled={props.readOnly || props.sending} rows={1} /><button type="button" className="queue-draft" aria-label={props.queueItems.length ? `Prompt queue, ${props.queueItems.length} waiting` : "Queue message"} disabled={props.readOnly || props.sending} onClick={() => props.draft.trim() || props.attachments.length ? props.onQueue() : setQueueOpen(true)}>⌛{props.queueItems.length > 0 && <b>{props.queueItems.length > 9 ? "9+" : props.queueItems.length}</b>}</button><button type="button" className="expand-writer" aria-label="Open large writing area" disabled={props.readOnly} onClick={() => setWritingMode(true)}>↗</button></div><button aria-label="Send now" disabled={props.readOnly || props.sending || (!props.draft.trim() && props.attachments.length === 0)}>{props.sending ? "…" : "↑"}</button></form>
      </div>
      {writingMode && <form className="writing-mode" onSubmit={(event) => { setWritingMode(false); props.onSubmit(event); }}><header><button type="button" onClick={() => setWritingMode(false)}>Done</button><strong>Write message</strong><button disabled={props.sending || (!props.draft.trim() && props.attachments.length === 0)}>{props.sending ? "…" : "Send"}</button></header><textarea autoFocus aria-label="Expanded terminal input" value={props.draft} onChange={(event) => props.onDraft(event.target.value)} onPaste={(event) => { const images = [...event.clipboardData.items].filter((item) => item.type.startsWith("image/")).map((item) => item.getAsFile()).filter((file): file is File => Boolean(file)).slice(0, 4 - props.attachments.length); if (images.length) { event.preventDefault(); images.forEach(props.onImage); } }} placeholder="Write your full message…" /><footer><button type="button" onClick={() => imageInputRef.current?.click()}>＋ Image</button><button type="button" disabled={props.sending || (!props.draft.trim() && props.attachments.length === 0)} onClick={() => { setWritingMode(false); props.onQueue(); }}>⌛ Queue</button><span>{props.draft.length.toLocaleString()} characters</span></footer></form>}
      {queueOpen && <PromptQueueSheet items={props.queueItems} busy={props.sending} onClose={() => setQueueOpen(false)} onUpdate={props.onQueueUpdate} onMove={props.onQueueMove} onSend={props.onQueueSend} onRemove={props.onQueueRemove} />}
    </div>
  );
}

function PromptQueueSheet({ items, busy, onClose, onUpdate, onMove, onSend, onRemove }: { items: PromptQueueItem[]; busy: boolean; onClose: () => void; onUpdate: (id: string, text: string) => Promise<void>; onMove: (id: string, direction: number) => Promise<void>; onSend: (id: string) => Promise<void>; onRemove: (id: string) => Promise<void> }) {
  return <><button className="queue-backdrop" aria-label="Close prompt queue" onClick={onClose} /><section className="queue-sheet" role="dialog" aria-modal="true" aria-label="Prompt queue"><header><div><strong>Prompt queue</strong><span>{items.length ? `${items.length} waiting · one sent after each agent stop` : "Send thoughts later without interrupting the agent"}</span></div><button onClick={onClose}>×</button></header>{items.length === 0 ? <div className="queue-empty"><span>⌛</span><strong>Nothing queued</strong><p>Write in the composer and tap the hourglass to send it after the agent finishes its current turn.</p></div> : <div className="queue-list">{items.map((item, index) => <PromptQueueRow item={item} index={index} count={items.length} busy={busy} onUpdate={onUpdate} onMove={onMove} onSend={onSend} onRemove={onRemove} key={item.id} />)}</div>}</section></>;
}

function PromptQueueRow({ item, index, count, busy, onUpdate, onMove, onSend, onRemove }: { item: PromptQueueItem; index: number; count: number; busy: boolean; onUpdate: (id: string, text: string) => Promise<void>; onMove: (id: string, direction: number) => Promise<void>; onSend: (id: string) => Promise<void>; onRemove: (id: string) => Promise<void> }) {
  const [value, setValue] = useState(item.text);
  return <article className="queue-item"><div className="queue-item-head"><span>Next {index ? `+${index}` : ""}</span>{item.lastError && <em>{item.lastError}</em>}<div><button aria-label="Move prompt earlier" disabled={busy || index === 0} onClick={() => onMove(item.id, -1)}>↑</button><button aria-label="Move prompt later" disabled={busy || index === count - 1} onClick={() => onMove(item.id, 1)}>↓</button></div></div><textarea aria-label={`Queued prompt ${index + 1}`} value={value} maxLength={32_000} onChange={(event) => setValue(event.target.value)} onBlur={() => { if (value.trim() && value.trim() !== item.text) onUpdate(item.id, value); }} /><footer><button className="queue-remove" disabled={busy} onClick={() => onRemove(item.id)}>Remove</button><button className="queue-send" disabled={busy || !value.trim()} onClick={async () => { if (value.trim() !== item.text) await onUpdate(item.id, value); await onSend(item.id); }}>Send now</button></footer></article>;
}

function HealthPanel({ workspace, terminal, onChanged, onNotice }: { workspace: Workspace; terminal: Terminal; onChanged: () => void; onNotice: (message: string) => void }) {
  const [overview, setOverview] = useState<Overview | null>(null); const [busy, setBusy] = useState(false); const load = useCallback(async () => { try { setOverview(await api<Overview>(`/api/workspaces/${workspace.id}/overview`)); } catch (error) { onNotice(error instanceof Error ? error.message : "Health unavailable"); } }, [workspace.id, onNotice]);
  useEffect(() => { const kickoff = setTimeout(load, 0); const poll = setInterval(load, 10_000); return () => { clearTimeout(kickoff); clearInterval(poll); }; }, [load]);
  async function mutate(path: string, body = "{}") { setBusy(true); try { await api(path, { method: "POST", body }); await load(); await onChanged(); } catch (error) { onNotice(error instanceof Error ? error.message : "Action failed"); } finally { setBusy(false); } }
  if (!overview) return <div className="detail-loading">Reading session health…</div>; const progress = overview.todos.progress; const state = overview.status.effective || overview.status.inferred || "ready";
  return <section className="health-page"><div className="health-hero"><span className={`status-orb ${state === "working" ? "working" : state === "done" ? "done" : "ready"}`} /><div><p>Session state</p><h2>{state}</h2><span>{overview.status.signals?.any_agent_needs_input ? "Agent is waiting for input" : overview.status.signals?.is_git_dirty ? "Working tree has changes" : "No blockers reported"}</span></div></div><div className="metric-grid"><div><span>CPU</span><strong>{overview.metrics?.cpuPercent.toFixed(1) || "0"}%</strong></div><div><span>Memory</span><strong>{formatBytes(overview.metrics?.memoryBytes)}</strong></div><div><span>Processes</span><strong>{overview.metrics?.processCount || 0}</strong></div></div><div className="health-section"><div className="section-heading"><div><h2>Agent tasks</h2><p>{progress.completed} of {progress.total} complete</p></div><span>{progress.total ? Math.round(progress.completed / progress.total * 100) : 0}%</span></div><div className="progress-track"><i style={{ width: `${progress.total ? progress.completed / progress.total * 100 : 0}%` }} /></div>{overview.todos.items.length === 0 ? <p className="muted empty-line">No structured tasks in this workspace.</p> : <div className="todo-list">{overview.todos.items.map((todo) => <button disabled={busy} key={todo.id} onClick={() => mutate(`/api/workspaces/${workspace.id}/todos/${todo.id}/${todo.state === "completed" ? "uncheck" : "check"}`)}><i className={todo.state}>{todo.state === "completed" ? "✓" : todo.state === "in-progress" ? "◐" : ""}</i><span>{todo.text}</span></button>)}</div>}</div><div className="health-section recovery"><h2>Recovery</h2><p>Restart the current terminal shell if it is stuck. Your workspace and other terminals stay open.</p><button disabled={busy} onClick={() => mutate(`/api/workspaces/${workspace.id}/respawn`, JSON.stringify({ surfaceId: terminal.id }))}>Restart current terminal</button><button className="danger-button" disabled={busy} onClick={() => { if (confirm(`Close “${workspace.title}”?`)) mutate(`/api/workspaces/${workspace.id}/close`); }}>Close workspace</button></div></section>;
}

function ChangesPanel({ repo, onMarkdown }: { repo: Repo | null; onMarkdown: (path: string) => void }) {
  const [changes, setChanges] = useState<Changes | null>(null); const [selected, setSelected] = useState<ChangedFile | null>(null); const [patch, setPatch] = useState(""); const [loading, setLoading] = useState(false); const [error, setError] = useState("");
  const load = useCallback(async () => { if (!repo) return; setLoading(true); try { setChanges(await api<Changes>(`/api/repos/${repo.id}/changes`)); setError(""); } catch (cause) { setError(cause instanceof Error ? cause.message : "Changes unavailable"); } finally { setLoading(false); } }, [repo]);
  useEffect(() => { const timer = setTimeout(load, 0); return () => clearTimeout(timer); }, [load]);
  async function openFile(file: ChangedFile, staged = file.area === "staged") { if (!repo) return; setSelected(file); setLoading(true); try { const result = await api<{ patch: string }>(`/api/repos/${repo.id}/diff?file=${encodeURIComponent(file.path)}&staged=${staged ? "1" : "0"}`); setPatch(result.patch || "No textual diff."); } catch (cause) { setPatch(cause instanceof Error ? cause.message : "Diff unavailable"); } finally { setLoading(false); } }
  if (!repo) return <Empty icon="⌁" title="Repository not catalogued" body="Change review is available for projects inside the approved karven and rekord roots." />; if (error) return <Empty icon="!" title="Could not read changes" body={error} />; if (selected) return <section className="diff-view"><header><button onClick={() => { setSelected(null); setPatch(""); }}>‹ Files</button><div><strong>{selected.path.split("/").pop()}</strong><span>{selected.path}</span></div>{/\.(md|markdown)$/i.test(selected.path) && <button className="read-file-button" onClick={() => onMarkdown(selected.path)}>Read</button>}</header><pre>{loading ? "Loading diff…" : patch}</pre></section>;
  return <section className="changes-page"><div className="changes-summary"><div><p className="eyebrow">{repo.branch}</p><h2>{changes?.files.length || 0} changed files</h2><span>{changes?.recentCommit ? `Latest: ${changes.recentCommit.hash} ${changes.recentCommit.subject}` : "No commits yet"}</span></div><button onClick={load}>↻</button></div>{loading && !changes ? <div className="detail-loading">Reading Git state…</div> : changes?.files.length === 0 ? <Empty icon="✓" title="Working tree clean" body="There are no staged, unstaged, or untracked changes." /> : <div className="file-list">{changes?.files.map((file) => <button key={file.path} onClick={() => openFile(file)}><span className={`file-status s-${file.status.toLowerCase()}`}>{file.status}</span><div><strong>{file.path.split("/").pop()}</strong><span>{file.path}</span></div><em>{file.areas.join(" + ")}</em><b>›</b></button>)}</div>}</section>;
}

function SettingsView({ bootstrap, readOnly, installable, onReadOnly, onInstall, onApps, onLogout, onNotice }: { bootstrap: Bootstrap | null; readOnly: boolean; installable: boolean; onReadOnly: (value: boolean) => void; onInstall: () => void; onApps: () => void; onLogout: () => void; onNotice: (message: string) => void }) { return <section className="subpage"><p className="eyebrow">COMPANION</p><h1>Settings</h1><div className="settings-list"><div className="setting-row"><div><strong>Connection</strong><span>{bootstrap?.connected ? bootstrap.host?.mac_display_name || "Connected to cmux" : "Waiting for cmux"}</span></div><i className={bootstrap?.connected ? "good" : ""}>{bootstrap?.connected ? "Online" : "Offline"}</i></div><label className="setting-row"><div><strong>Read-only protection</strong><span>Prevent accidental terminal input</span></div><input type="checkbox" checked={readOnly} onChange={(event) => onReadOnly(event.target.checked)} /></label><button className="setting-row setting-button" onClick={onApps}><div><strong>Local apps</strong><span>Manage private Tailscale preview links</span></div><i>Open ›</i></button></div><PushSettings onNotice={onNotice} />{installable && <button className="primary-button install-button" onClick={onInstall}>Add companion to home screen</button>}<div className="privacy-note"><strong>Private by design</strong><p>The backend listens only on this Mac. Access is encrypted and routed through your Tailscale network; pairing is still required per browser.</p></div><button className="logout-button" onClick={onLogout}>Unpair this device</button></section>; }

function PushSettings({ onNotice }: { onNotice: (message: string) => void }) {
  type AlertSettings = { attention: boolean; completion: boolean; failure: boolean; pullRequest: boolean; preview: boolean; hideContent: boolean; quietEnabled: boolean; quietStart: string; quietEnd: string };
  const [subscription, setSubscription] = useState<PushSubscription | null>(null); const [status, setStatus] = useState<{ supported: boolean; publicKey?: string; subscribed: boolean; settings?: AlertSettings } | null>(null); const [busy, setBusy] = useState(false); const supported = typeof window !== "undefined" && "serviceWorker" in navigator && "PushManager" in window && "Notification" in window;
  const load = useCallback(async () => { if (!supported) { setStatus({ supported: false, subscribed: false }); return; } const registration = await navigator.serviceWorker.ready; const current = await registration.pushManager.getSubscription(); setSubscription(current); setStatus(await api(`/api/push/status${current ? `?endpoint=${encodeURIComponent(current.endpoint)}` : ""}`)); }, [supported]);
  useEffect(() => { const timer = setTimeout(() => load().catch(() => setStatus({ supported: false, subscribed: false })), 0); return () => clearTimeout(timer); }, [load]);
  async function enable() { setBusy(true); try { const registration = await navigator.serviceWorker.ready; const base = await api<{ publicKey: string }>("/api/push/status"); const permission = await Notification.requestPermission(); if (permission !== "granted") throw new Error("Notification permission was not granted"); const created = await registration.pushManager.subscribe({ userVisibleOnly: true, applicationServerKey: urlBase64ToBytes(base.publicKey) }); await api("/api/push/subscribe", { method: "POST", body: JSON.stringify({ subscription: created.toJSON() }) }); setSubscription(created); await load(); onNotice("Background alerts enabled"); } catch (error) { onNotice(error instanceof Error ? error.message : "Could not enable alerts"); } finally { setBusy(false); } }
  async function disable() { if (!subscription) return; setBusy(true); try { await api("/api/push/unsubscribe", { method: "POST", body: JSON.stringify({ endpoint: subscription.endpoint }) }); await subscription.unsubscribe(); setSubscription(null); await load(); } catch (error) { onNotice(error instanceof Error ? error.message : "Could not disable alerts"); } finally { setBusy(false); } }
  async function update<K extends keyof AlertSettings>(key: K, value: AlertSettings[K]) { if (!subscription || !status?.settings) return; const settings = { ...status.settings, [key]: value }; setStatus({ ...status, settings }); try { await api("/api/push/settings", { method: "POST", body: JSON.stringify({ endpoint: subscription.endpoint, settings }) }); } catch (error) { onNotice(error instanceof Error ? error.message : "Could not save alert settings"); await load(); } }
  async function sendTest() { if (!subscription) return; setBusy(true); try { const result = await api<{ sent: number; error?: { message?: string } | null }>("/api/push/test", { method: "POST", body: JSON.stringify({ endpoint: subscription.endpoint }) }); onNotice(result.sent ? "Test alert delivered" : result.error?.message || "No alert was delivered"); if (!result.sent) await load(); } catch (error) { onNotice(error instanceof Error ? error.message : "Could not send the test alert"); } finally { setBusy(false); } }
  const standalone = typeof window !== "undefined" && (matchMedia("(display-mode: standalone)").matches || (navigator as Navigator & { standalone?: boolean }).standalone);
  return <div className="push-card"><div className="push-title"><div><strong>Background alerts</strong><span>Contextual decisions, failures, PRs, and previews</span></div>{status?.subscribed ? <button disabled={busy} onClick={disable}>Disable</button> : <button className="approve" disabled={busy || !supported} onClick={enable}>Enable</button>}</div>{!supported && <p className="push-guidance">On iPhone, add this web app to your Home Screen first, then open it there to enable push alerts.</p>}{supported && !standalone && /iPhone|iPad/.test(navigator.userAgent) && <p className="push-guidance">Install to your Home Screen for reliable iPhone background alerts.</p>}{status?.subscribed && status.settings && <div className="push-options"><label><span><strong>Needs attention</strong><small>Permissions, questions, plans</small></span><input type="checkbox" checked={status.settings.attention} onChange={(event) => update("attention", event.target.checked)} /></label><label><span><strong>Failures</strong><small>Tests, builds, and command errors</small></span><input type="checkbox" checked={status.settings.failure} onChange={(event) => update("failure", event.target.checked)} /></label><label><span><strong>Agent completed</strong><small>Work ready for review</small></span><input type="checkbox" checked={status.settings.completion} onChange={(event) => update("completion", event.target.checked)} /></label><label><span><strong>Pull requests</strong><small>Checks and review changes</small></span><input type="checkbox" checked={status.settings.pullRequest} onChange={(event) => update("pullRequest", event.target.checked)} /></label><label><span><strong>Local apps</strong><small>Detected and ready previews</small></span><input type="checkbox" checked={status.settings.preview} onChange={(event) => update("preview", event.target.checked)} /></label><label><span><strong>Quiet hours</strong><small>Silence alerts during this window</small></span><input type="checkbox" checked={status.settings.quietEnabled} onChange={(event) => update("quietEnabled", event.target.checked)} /></label>{status.settings.quietEnabled && <div className="quiet-hours"><label>From<input type="time" value={status.settings.quietStart} onChange={(event) => update("quietStart", event.target.value)} /></label><label>Until<input type="time" value={status.settings.quietEnd} onChange={(event) => update("quietEnd", event.target.value)} /></label></div>}<label><span><strong>Hide details</strong><small>Use discreet lock-screen text</small></span><input type="checkbox" checked={status.settings.hideContent} onChange={(event) => update("hideContent", event.target.checked)} /></label><button className="test-alert" disabled={busy} onClick={sendTest}>Send test alert</button></div>}</div>;
}

function urlBase64ToBytes(value: string) { const padding = "=".repeat((4 - value.length % 4) % 4); const raw = atob((value + padding).replaceAll("-", "+").replaceAll("_", "/")); return Uint8Array.from([...raw].map((char) => char.charCodeAt(0))); }
function BottomNav({ view, onView, attention }: { view: View; onView: (view: View) => void; attention: number }) { return <nav className="bottom-nav">{[["sessions", "⌂", "Sessions"], ["inbox", "◫", "Inbox"], ["launch", "＋", "Launch"], ["settings", "⚙", "Settings"]].map(([id, icon, label]) => <button className={view === id ? "active" : ""} onClick={() => onView(id as View)} key={id}><span>{icon}{id === "inbox" && attention > 0 && <i>{attention > 9 ? "9+" : attention}</i>}</span><small>{label}</small></button>)}</nav>; }
function Empty({ icon, title, body, action }: { icon: string; title: string; body: string; action?: React.ReactNode }) { return <div className="empty-card"><span>{icon}</span><strong>{title}</strong><p>{body}</p>{action}</div>; }
function WorkspaceSkeleton() { return <div className="workspace-card skeleton"><i /><i /><i /></div>; }
function LoadingScreen() { return <main className="center-screen"><div className="brand-mark large">c</div><p>Opening companion…</p></main>; }
function PairScreen({ offline, token, error, onToken, onPair }: { offline: boolean; token: string; error: string; onToken: (value: string) => void; onPair: (event: FormEvent) => void }) { return <main className="pair-screen"><div className="pair-card"><div className="brand-mark large">c</div><p className="eyebrow">PRIVATE REMOTE ACCESS</p><h1>{offline ? "Your companion is offline." : "Pair this phone."}</h1><p>{offline ? "Connect to Tailscale and reload this page." : "Enter the private pairing code shown by the installer on your Mac."}</p>{offline ? <button className="primary-button" onClick={() => location.reload()}>Try again</button> : <form onSubmit={onPair}><input type="password" autoComplete="one-time-code" value={token} onChange={(event) => onToken(event.target.value)} placeholder="Pairing code" autoFocus /><button className="primary-button" disabled={!token.trim()}>Pair securely</button>{error && <p className="form-error">{error}</p>}</form>}<small>Tailscale connection required</small></div></main>; }
